#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#c29df1"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# Autostart---------------------------------

pgrep -x picom > /dev/null || picom & 
pgrep -x feh > /dev/null || feh --bg-fill /home/nolood/Pictures/wallpapers/0010.jpg & 
pgrep -x polybar > /dev/null || sh ~/.config/polybar/custom/launch.sh &

# Resolution--------------------------------

xrandr --output eDP-1 --mode 1920x1200
